version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  apt_packages:
    - g++-11
    - gcc-11

  environment:
    CC: gcc
    CXX: g++

  jobs:
    pre_build:
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
      - gcc --version
      - g++ --version
      - python -m pip install -r requirements.txt
      - python -m pip install -r requirements_doc.txt
      - python -m pip install pypandoc_binary
      - python setup.py build_ext --inplace
      - sphinx-build -M html source outputdir

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false

submodules:
  recursive: true
