version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - git clone https://github.com/p-ranav/csv2.git libs/csv2
      - python -m pip install -r requirements.txt
      - python -m pip install -r requirements_doc.txt
      - python -m pip install pypandoc_binary
      - python setup.py build_ext --inplace
      - sphinx-build -M html source outputdir

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_doc.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false

submodules:
  include: all
  recursive: true
